---
title: "R Notebook"
output: html_notebook
---

```{r Loading Packages}
# Load CRAN packages
library(tidyverse)
library(vegan)
library(ape)

# Load Bioconductor packages
library(phyloseq)
library(DESeq2)

#Install package from Github
if (!requireNamespace("devtools", quietly = TRUE)){install.packages("devtools")}
devtools::install_github("jbisanz/qiime2R")
remotes::install_github("vmikk/metagMisc")

#Loading special packages
library(qiime2R)

# Load additional ggplot packages
library(ggplot2)
library(ggthemes)

```

```{r Import from QIIME and Metadata Handling}
# Define name of metadata file
metadata_file <- "hiseas_metadata.txt"

# Load the metadata file
biom_file <- import_biom("table-with-taxonomy.biom")
metadata  <- import_qiime_sample_data("hiseas_metadata.txt")
tree      <- read_tree_greengenes("tree.nwk")

# Convert from multichotomous to dichotmous tree
tree <- multi2di(tree)

# Combine all information into a single phyloseq object
physeq <- merge_phyloseq(biom_file, metadata, tree)
physeq_rar <- rarefy_even_depth(physeq, sample.size = 10000)

colnames(tax_table(physeq)) <- c("Kingdom", "Phylum", "Class","Order", "Family",
                                 "Genus", "Species")
tax_table(physeq)
```


```{r Differential Abundance Analysis}
# Calculate relative abundance
calculate_relative_abundance <- function(x) x / sum(x)
total_counts <- taxa_sums(physeq)
relative_abundance <- calculate_relative_abundance(total_counts)

abundant <- relative_abundance > 0.0005 
abundant_taxa <- prune_taxa(abundant, physeq)

# Calculate geometric mean 
calculate_gm_mean <- function(x, na.rm = TRUE) {
  exp(sum(log(x[x > 0]), na.rm = na.rm) / length(x))
}

# DESeq object creation and exploration
plastic <- subset_samples(physeq, orig_env_material == "plastic")

plastic_counts <-taxa_sums(plastic)
relative_abundance_plastic <- calculate_relative_abundance(plastic_counts)
abundant_plastic <- relative_abundance_plastic > 0.0005
abundant_plastic_taxa <- prune_taxa(abundant_plastic, plastic)

abundant_plastic_genera <- tax_glom(abundant_plastic_taxa, taxrank = "Genus")
abundant_plastic_genera

deseq_plastic <- phyloseq_to_deseq2(abundant_plastic_genera, ~feature)
as_tibble(colData(deseq_plastic))

# Use Bedroom as Reference
deseq_plastic$feature <- relevel(deseq_plastic$feature, ref = "bed base")
geo_means <- apply(counts(deseq_plastic), 1, calculate_gm_mean)
deseq_plastic <- estimateSizeFactors (deseq_plastic, geoMeans = geo_means)
deseq_plastic <- DESeq(deseq_plastic, fitType = "local")

# Extracting differential abundant microbes
resultsNames(deseq_plastic)

# Living Room vs Bedroom
living_bed_diff_abund <- results(deseq_plastic, name = "feature_living.room_vs_bed.base")

alpha <- 0.01
(significant_living_bed <- living_bed_diff_abund %>% 
  as.data.frame() %>% 
  filter(padj < alpha))

genera_df <- as.data.frame(tax_table(abundant_plastic_genera))
(significant_living_bed <- significant_living_bed %>% 
  merge(genera_df, by = "row.names") %>% 
  arrange(log2FoldChange))


ggplot(significant_living_bed, aes(x = log2FoldChange, y = reorder(Genus, -log2FoldChange), Genus)) +
  geom_bar(stat = "identity") +
  labs(title = "Living Room vs Bed",
       x = expression(log[2]~fold~change),
       y = "Genus") +
  theme_bw(base_size = 8) +
  scale_x_continuous(labels=waiver(), limits=c(-10,25))

# Use Bathroom Reference
deseq_plastic$feature <- relevel(deseq_plastic$feature, ref = "composting toilet")
geo_means <- apply(counts(deseq_plastic), 1, calculate_gm_mean)
deseq_plastic <- estimateSizeFactors (deseq_plastic, geoMeans = geo_means)
deseq_plastic <- DESeq(deseq_plastic, fitType = "local")

resultsNames(deseq_plastic)

# Bedroom vs Bathroom
bed_toilet_diff_abund <- results(deseq_plastic, name = "feature_bed.base_vs_composting.toilet")

alpha <- 0.01
(significant_bed_toilet <- bed_toilet_diff_abund %>% 
  as.data.frame() %>% 
  filter(padj < alpha))

genera_df <- as.data.frame(tax_table(abundant_plastic_genera))
(significant_bed_toilet <- significant_bed_toilet %>% 
  merge(genera_df, by = "row.names") %>% 
  arrange(log2FoldChange))

ggplot(significant_bed_toilet, aes(x = log2FoldChange, y = reorder(Genus, -log2FoldChange), Genus)) +
  geom_bar(stat = "identity") +
  labs(title = "Bed vs Toilet",
       x = expression(log[2]~fold~change),
       y = "Genus") +
  theme_bw(base_size = 10) +
  scale_x_continuous(labels=waiver(), limits=c(-10,25))

# Living room vs Bathroom
living_toilet_diff_abund <- results(deseq_plastic, name = "feature_living.room_vs_composting.toilet")

alpha <- 0.01
(significant_living_toilet <- living_toilet_diff_abund %>% 
  as.data.frame() %>% 
  filter(padj < alpha))

genera_df <- as.data.frame(tax_table(abundant_plastic_genera))
(significant_living_toilet <- significant_living_toilet %>% 
  merge(genera_df, by = "row.names"))

ggplot(significant_living_toilet, aes(x = log2FoldChange, y = reorder(Genus, -log2FoldChange), Genus)) +
  geom_bar(stat = "identity") +
  labs(title = "Living Room vs Toilet",
       x = expression(log[2]~fold~change),
       y = "Genus") +
  theme_bw(base_size = 8) +
  scale_x_continuous(labels=waiver(), limits=c(-10,25))
```


```{r Principle Coordinate Analysis Plot}
ord <- ordinate(physeq, method = "PCoA", distance = "wunifrac")

no_water <- subset_samples(physeq, orig_env_material != "water")
no_water_samplingequipment <- subset_samples(no_water, orig_env_material != "samplingequipment")
ord <- ordinate(no_water_samplingequipment, method = "PCoA", distance = "wunifrac")
plot_ordination(physeq,
                ord,
                color = "orig_env_material")+
  # Define title of plot
  labs(title = "PCoA (weighted UniFrac)") +
  theme_bw()+
  stat_ellipse(type = "norm", size = 0.5)

#Data processing 
dataset$sample_sums()
#Filter by metadata
#Filter the samples to only include surface samples
dataset$sample_table <- dataset$sample_table %>% filter(`collection_device` == "swab")
dataset$tidy_dataset()
#Rarefy filtered data
dataset$rarefy_samples(sample.size = 1000)

#Calculate relative abundance
dataset$cal_abund(rel=T)
typeof(dataset$taxa_abund)
names(dataset$taxa_abund)
dataset$taxa_abund$Class [1:5,1:5]

#Removing low abundant features
total_counts <- dataset$taxa_sums()
relative_abundance <- calculate_relative_abundance(total_counts)
#filter out low abundant features
abundant <- relative_abundance > 0.0005 
dataset$tidy_dataset()

#extract relative abundance information on Genera
genera_RA <- dataset$taxa_abund$Genus %>% as_tibble(rownames = "Feature_Taxonomy")
#Only a snippet shown
head(genera_RA)
genera_RA <- genera_RA %>% pivot_longer(-Feature_Taxonomy, values_to = "Relative_Abundance", names_to = "SampleID")
#Now we can join this with the metadata and plot
genera_RA <- genera_RA %>% left_join(dataset$sample_table)
#Split up feature taxonomy
genera_RA <- genera_RA %>% separate(Feature_Taxonomy, into = c("k","p","c","o","f","g"), sep = "\\|")
ggplot(filter(genera_RA, g =="g__Akkermansia"), aes(x=subject, y = Relative_Abundance)) +
  geom_boxplot()

#Creating a Venn Diagram comparing wood and plastic
surface_venn_dataset<- meco_data$merge_samples(use_group = "orig_env_material")
surface_venn_dataset
# create trans_venn object
t1 <- trans_venn$new(surface_venn_dataset, ratio = "numratio")
t1$plot_venn()
labs(title = "PCoA (weighted UniFrac)", colour = "Surface Type") +
  theme_classic()+
  stat_ellipse(type = "norm", size = 0.5)

# PCoA Plastic Only
plastic_only <- subset_samples(no_water_samplingequipment, orig_env_material != "wood")
ord <- ordinate(plastic_only, method = "PCoA", distance = "wunifrac")
plot_ordination(physeq_rar,
                ord,
                color = "description")+
  # Define title of plot
  labs(title = "PCoA (weighted UniFrac)", colour = "Location") +
  theme_classic()+
  stat_ellipse(type = "norm", size = 0.5)

Taxonomy <- read_qza
```

```{r Creating Venn Diagrams of Taxonomic Analysis}
#VennDiagram of Different Genera
grid.newpage()
draw.triple.venn(area1 = 236, area2 = 224, area3 = 233, n12 = 214, n23 = 212, n13 = 223, n123 = 206,
                 category = c("Bedroom", "Bathroom", "Living Room"), 
                 col ="black", fill=c("Light Blue", "orange", "pink"), 
                 lty = "blank",
                 cex =2,
                 cat.cex = 1.2,
                 sep.dist = 0.2,
                print.mode=c("raw","percent"))

#Venn Diagram of Different Species
grid.newpage()
draw.triple.venn(area1 = 306, area2 = 295, area3 = 307, n12 = 275, n23 = 277, n13 = 286, n123 = 265,
                 category = c("Bedroom", "Bathroom", "Living Room"), 
                 col ="black", fill=c("Light Blue", "orange", "pink"), 
                 lty = "blank",
                 cex = 1.6,
                 cat.cex = 1.2,
                 sep.dist = 0.1,
                 print.mode=c("raw","percent"))
```

